slug: personal-china
id_grupo: 1212
nombre: 'Personal China'
descripcion: 'Equipo de trabajadores chinos'
menus:
  -
    id_menu: 1
    titulo: Inicio
    url: InicioController
  -
    id_menu: 175
    titulo: 'Agente de Compra'
    url: '#'
  -
    id_menu: 178
    titulo: 'Agente de Compra → Cotización Garantizada'
    url: AgenteCompra/PedidosGarantizados/listar
  -
    id_menu: 180
    titulo: 'Agente de Compra → Orden de Compra'
    url: AgenteCompra/PedidosPagados/listar
